Issue #8: Adding a personl page
BuidlGuidl/batch4.buidlguidl.com pull request #17
Opened 2024-04-09 18:14 UTC by Welith

## Description

_Added the `.tsx` file of my landing page, containing a brief bio and some referral links to my socials._
<img width="1677" alt="Screenshot 2024-04-09 at 21 07 14" src="https://github.com/BuidlGuidl/batch4.buidlguidl.com/assets/33628158/18c00d97-1217-4151-ae2a-c66190a85fde">

## Additional Information

- [x] I have read the [contributing docs](/scaffold-eth/scaffold-eth-2/blob/main/CONTRIBUTING.md) (if this is your first contribution)
- [x] This is not a duplicate of any [existing pull request](https://github.com/scaffold-eth/scaffold-eth-2/pulls)

## Related Issues

* Ref #8

Your ENS/address:
0xF11046328814004583c8e74050f0d59520f53e90

2024-04-10 10:10 UTC, carletex commented on packages/nextjs/app/builders/0xF11046328814004583c8e74050f0d59520f53e90/page.tsx
> +  { name: "Twitter", url: "https://twitter.com/bo4ka7a" }, // Replace with URL
I think you can remove the comment at the end :D

2024-04-10 10:11 UTC, carletex commented on packages/nextjs/app/builders/0xF11046328814004583c8e74050f0d59520f53e90/page.tsx
> +const Home: React.FC = () => {
Let's choose a different name + it should be NextPage (from "next") Instead of React.FC

2024-04-10 10:11 UTC, carletex commented on packages/nextjs/app/builders/0xF11046328814004583c8e74050f0d59520f53e90/page.tsx
> +    <div style={{ textAlign: "center", paddingTop: "50px" }}>
We are using [Tailwind](https://tailwindcss.com/), so you don't need to use inline styles.

2024-04-10 10:14 UTC, carletex commented on packages/nextjs/app/builders/0xF11046328814004583c8e74050f0d59520f53e90/page.tsx
> +        <img
This is causing a linting issue: https://github.com/BuidlGuidl/batch4.buidlguidl.com/actions/runs/8620398825/job/23654029724?pr=17

![image](https://github.com/BuidlGuidl/batch4.buidlguidl.com/assets/2486142/9f31839a-15c3-460e-95d9-4e4116a78829)

---

Check https://github.com/BuidlGuidl/batch4.buidlguidl.com/pull/13#discussion_r1557610727

2024-04-10 10:14 UTC, carletex commented on packages/nextjs/app/builders/0xF11046328814004583c8e74050f0d59520f53e90/page.tsx
> +    <div style={{ textAlign: "center", paddingTop: "50px" }}>
Same for the other inlined styles.

2024-04-10 10:14 UTC, carletex requested changes
Thanks for this @Welith 

Left some review comments!

2024-04-10 17:02 UTC, Welith commented
Thanks for the tips @carletex Addressed the issues. Check them when possible.

2024-04-11 08:20 UTC, carletex commented
Good stuff @Welith !!

This component still is named "Home", but that's ok, was a nitpick. ALl the other stuff looks great. Mergin!

2024-04-11 08:20 UTC, merged